apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
data:
  named.conf: |
    options {
      directory "/var/cache/bind";
      allow-query { any; };
      recursion yes;
      forwarders {
        8.8.8.8;
        8.8.4.4;
      };
    };

    zone "dmm.tt.pk" {
      type master;
      file "/var/cache/bind/db.dmm.tt.pk";
    };

  db.dmm.tt.pk: |
    $TTL    604800
    @       IN      SOA     ns1.dmm.tt.pk. admin.dmm.tt.pk. (
                            1         ; Serial
                       604800         ; Refresh
                        86400         ; Retry
                      2419200         ; Expire
                       604800 )       ; Negative Cache TTL

    @       IN      NS      ns1.dmm.tt.pk.
    ns1     IN      A       10.202.99.61
    traefik     IN      A       10.202.99.60
