apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: ubuntu/bind9
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: bind9-config
          mountPath: /etc/bind           # ConfigMap
          readOnly: true
        - name: bind9-data
          mountPath: /var/cache/bind     # PVC
      volumes:
      - name: bind9-config
        configMap:
          name: bind9-config
      - name: bind9-data
        persistentVolumeClaim:
          claimName: bind9-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind9-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
