apiVersion: v1
kind: Service
metadata:
  name: bind9
spec:
  selector:
    app: bind9
  type: LoadBalancer
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
